(define (problem robot-prob)
  (:domain robot-domain)
  (:objects rm1 rm2 obj1 obj2)
  (:init (Room rm1)
	  (Room rm2)
	  (Object obj1) (object obj2) (object robot)
	  (Connected rm1 rm2)
	  (Connected rm2 rm1)
	  (AtRoom obj1 rm2) (at obj2 rm2)
	  (RobotNotHoldingObj)
	  (AtRoom robot rm1))
  (:goal (AtRoom obj1 rm1)))
